export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_ERROR_SUCCESS";
export const GET_ALL_TODOS_ERROR = "GET_ALL_TODOS_ERROR";

export const APPLICATION_ERROR = "APPLICATION_ERROR";

export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_ERROR = "REMOVE_TODO_ERROR";
